{
 "title": "Shop API — SLO dashboard",
 "tags": [
  "sre",
  "capstone"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Request rate (RPS)",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(shop_api_http_requests_total[1m]))"
    }
   ]
  },
  {
   "title": "Error rate (5xx, 5m)",
   "type": "stat",
   "gridPos": { "x": 6, "y": 0, "w": 6, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "shop_api:error_rate5m" }
   ]
  },
  {
   "title": "p95 latency /work",
   "type": "stat",
   "gridPos": { "x": 12, "y": 0, "w": 6, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(shop_api_http_request_duration_seconds_bucket{route=\"/work\"}[5m])) by (le))"
    }
   ]
  },
  {
   "title": "shop-api replicas",
   "type": "stat",
   "gridPos": { "x": 18, "y": 0, "w": 6, "h": 4 },
   "targets": [
    {
     "expr": "count(shop_api_inflight_requests)"
    }
   ]
  },
  {
   "title": "Requests per second (per route)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 4, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(shop_api_http_requests_total[1m])) by (route)",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "p50 / p95 / p99 latency",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 4, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(shop_api_http_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(shop_api_http_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(shop_api_http_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "CPU per pod",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 12, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"shop\", pod=~\"shop-api-.*\", container=\"shop-api\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "In-flight HTTP requests",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 12, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(shop_api_inflight_requests)"
    }
   ]
  }
 ]
}